"""Fabric Data Factory Migration Assistant (FDFMA) hand-off pack.

Turns the assessed estate into a ready-to-use bundle for Microsoft's
`FabricDataFactoryMigrationAssistant
<https://github.com/microsoft/fabric-toolbox/tree/main/tools/FabricDataFactoryMigrationAssistant>`_:

* one Synapse ARM template per workspace (when raw definitions were captured by a
  live inventory run) that the Assistant can profile and deploy directly;
* a ``handoff_manifest.json`` classifying every artifact into an FDFMA support
  tier (auto / partial / manual);
* a ``fdfma_scope.csv`` for spreadsheets / Power BI;
* a ``README.md`` with step-by-step instructions.

The manifest / CSV / README are derived from the standard inventory, so they are
produced even before raw definitions exist; only the ARM templates require a live
``inventory`` run (which retains the raw artifact bodies).
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from ..models.inventory import Inventory
from .arm_template import write_arm_template
from .csv_writer import write_csv
from .json_writer import write_json
from .markdown_writer import write_markdown

TOOL_NAME = "Fabric Data Factory Migration Assistant"
TOOL_URL = (
    "https://github.com/microsoft/fabric-toolbox/tree/main/tools/"
    "FabricDataFactoryMigrationAssistant"
)

# artifact collection -> (FDFMA tier, explanation). Tiers:
#   auto    - FDFMA transforms and deploys automatically.
#   manual  - FDFMA cannot migrate it; rebuild it separately (Copilot pack helps).
_SUPPORT: dict[str, tuple[str, str]] = {
    "pipelines": ("auto", "Transformed and deployed as Fabric Data Pipelines."),
    "triggers": ("auto", "Recreated as Fabric pipeline schedules (deployed disabled for testing)."),
    "linkedservices": ("auto", "Mapped to Fabric connections in the connection wizard."),
    "datasets": ("auto", "Embedded into activities as datasetSettings."),
    "notebooks": ("manual", "Migrate notebook code to a Fabric Notebook separately; the pipeline activity reference is re-wired."),
    "dataflows": ("manual", "Not supported by FDFMA — rebuild as Dataflow Gen2 (or a Spark notebook)."),
}

# ARM templates only carry the deployable/profilable set (notebooks are handled
# via the Copilot pack and carry large source bodies, so they are excluded).
_ARM_KINDS = ["linkedservices", "datasets", "dataflows", "pipelines", "triggers"]


def _counts(ws: Any) -> dict[str, int]:
    return {
        "pipelines": len(ws.pipelines),
        "triggers": len(ws.triggers),
        "linkedservices": len(ws.linked_services),
        "datasets": len(ws.datasets),
        "notebooks": len(ws.notebooks),
        "dataflows": len(ws.dataflows),
    }


def _artifacts(ws: Any) -> list[tuple[str, str]]:
    """Yield (kind, artifact_name) for every migratable artifact in a workspace."""
    rows: list[tuple[str, str]] = []
    for p in ws.pipelines:
        rows.append(("pipelines", p.name))
    for t in ws.triggers:
        rows.append(("triggers", t.name))
    for ls in ws.linked_services:
        rows.append(("linkedservices", ls.name))
    for d in ws.datasets:
        rows.append(("datasets", d.name))
    for n in ws.notebooks:
        rows.append(("notebooks", n.name))
    for df in ws.dataflows:
        rows.append(("dataflows", df.name))
    return rows


def _readme(manifest: dict[str, Any]) -> str:
    totals = manifest["totals"]
    have_arm = manifest["raw_definitions_available"]
    lines: list[str] = [
        f"# {TOOL_NAME} — hand-off pack\n",
        f"Generated by the Synapse \u2192 Fabric accelerator to feed the "
        f"[{TOOL_NAME}]({TOOL_URL}).\n",
        "The Assistant is a browser app that ingests a Synapse/ADF **ARM template**, "
        "profiles it, then deploys the supported artifacts to Microsoft Fabric.\n",
        "## What FDFMA will migrate for you\n",
        f"- **{totals['auto']}** artifacts are **auto-migratable** "
        "(pipelines, triggers, linked services, datasets).",
        f"- **{totals['manual']}** artifacts need **manual** work "
        "(notebooks \u2192 Fabric Notebooks; data flows \u2192 Dataflow Gen2). "
        "Use the Copilot optimization pack for these.\n",
        "## Support tiers\n",
        "| Artifact type | FDFMA tier | Notes |",
        "|---|---|---|",
    ]
    for kind, (tier, note) in _SUPPORT.items():
        lines.append(f"| {kind} | **{tier}** | {note} |")
    lines.append("\n## How to use this pack\n")
    if have_arm:
        lines += [
            "1. Open the Migration Assistant (deploy it from the "
            f"[repo]({TOOL_URL}) or run it locally).",
            "2. On the **Upload & Profile** step, upload the per-workspace ARM "
            "template from this folder (`<workspace>.arm.json`).",
            "3. Review the profiling report, then sign in and select your target "
            "Fabric workspace.",
            "4. Map connections, validate, and deploy. Schedules deploy **disabled** "
            "by default \u2014 enable them after testing.",
            "5. For every **manual** artifact listed in `fdfma_scope.csv`, use the "
            "Copilot optimization pack to rebuild it in Fabric.",
        ]
    else:
        lines += [
            "> \u26a0\ufe0f **No ARM templates were generated** because raw artifact "
            "definitions are not available. Re-run a **live** `inventory` "
            "(`python -m src.cli inventory`) against Azure to capture them, then "
            "re-run `migrate` \u2014 the accelerator will emit `<workspace>.arm.json` "
            "here automatically.",
            "",
            "Alternatively, export the ARM template manually from Synapse Studio "
            "(**Manage \u2192 ARM template \u2192 Export**) and upload that to the Assistant.",
            "",
            "Once you have a template, follow the Assistant's **Upload & Profile "
            "\u2192 Login \u2192 Deploy** wizard.",
        ]
    lines += [
        "\n## Security note\n",
        "Linked-service definitions may reference credentials. Synapse returns "
        "secrets as Key Vault references or `SecureString` placeholders (not "
        "plaintext), but review each `<workspace>.arm.json` before uploading and "
        "keep this folder local (it is git-ignored).\n",
    ]
    return "\n".join(lines)


def write_migration_assistant_pack(
    out_dir: str | Path,
    inventory: Inventory,
    raw_by_workspace: dict[str, dict[str, list[dict[str, Any]]]] | None = None,
) -> dict[str, Any]:
    """Write the FDFMA hand-off pack and return the manifest dict."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    raw_by_workspace = raw_by_workspace or {}
    have_arm = bool(raw_by_workspace)

    scope_rows: list[dict[str, Any]] = []
    ws_entries: list[dict[str, Any]] = []
    totals = {"auto": 0, "manual": 0}

    for ws in inventory.workspaces:
        name = ws.workspace.name
        counts = _counts(ws)
        auto = {k: counts[k] for k in counts if _SUPPORT[k][0] == "auto"}
        manual = {k: counts[k] for k in counts if _SUPPORT[k][0] == "manual"}
        totals["auto"] += sum(auto.values())
        totals["manual"] += sum(manual.values())

        arm_file = None
        raw = raw_by_workspace.get(name)
        if raw:
            arm_file = f"{name}.arm.json"
            write_arm_template(name, raw, out / arm_file, include=_ARM_KINDS)

        ws_entries.append({
            "workspace": name,
            "arm_template": arm_file,
            "auto_migratable": auto,
            "manual": manual,
        })
        for kind, artifact in _artifacts(ws):
            tier, note = _SUPPORT[kind]
            scope_rows.append({
                "workspace": name, "artifact": artifact, "type": kind,
                "fdfma_tier": tier, "note": note,
            })

    manifest = {
        "tool": TOOL_NAME,
        "tool_url": TOOL_URL,
        "raw_definitions_available": have_arm,
        "support_tiers": {k: {"tier": t, "note": n} for k, (t, n) in _SUPPORT.items()},
        "workspaces": ws_entries,
        "totals": totals,
    }

    write_json(manifest, out / "handoff_manifest.json")
    write_csv(scope_rows, out / "fdfma_scope.csv",
              ["workspace", "artifact", "type", "fdfma_tier", "note"])
    write_markdown(_readme(manifest), out / "README.md")
    return manifest
