table notebooks

	column name
		dataType: string
		sourceColumn: name

	column workspace
		dataType: string
		sourceColumn: workspace

	column language
		dataType: string
		sourceColumn: language

	column cell_count
		dataType: string
		sourceColumn: cell_count

	column uses_spark
		dataType: string
		sourceColumn: uses_spark

	column uses_delta
		dataType: string
		sourceColumn: uses_delta

	column uses_synapse_utils
		dataType: string
		sourceColumn: uses_synapse_utils

	column uses_spark_config
		dataType: string
		sourceColumn: uses_spark_config

	measure 'Notebook Count' = COUNTROWS('notebooks')

	measure 'Delta Notebooks %' = DIVIDE(CALCULATE(COUNTROWS('notebooks'),'notebooks'[uses_delta]="True"),COUNTROWS('notebooks'))

	partition notebooks = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataFolder & "notebooks.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true])
			in
			    Headers
