table pipelines

	column name
		dataType: string
		sourceColumn: name

	column workspace
		dataType: string
		sourceColumn: workspace

	column activity_count
		dataType: string
		sourceColumn: activity_count

	column parameter_count
		dataType: string
		sourceColumn: parameter_count

	column has_nested_activities
		dataType: string
		sourceColumn: has_nested_activities

	measure 'Pipeline Count' = COUNTROWS('pipelines')

	partition pipelines = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataFolder & "pipelines.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true])
			in
			    Headers
