table sql_pools

	column name
		dataType: string
		sourceColumn: name

	column workspace
		dataType: string
		sourceColumn: workspace

	column sku
		dataType: string
		sourceColumn: sku

	column tier
		dataType: string
		sourceColumn: tier

	column status
		dataType: string
		sourceColumn: status

	column is_serverless
		dataType: string
		sourceColumn: is_serverless

	column collation
		dataType: string
		sourceColumn: collation

	column table_count
		dataType: string
		sourceColumn: table_count

	column total_size_mb
		dataType: double
		sourceColumn: total_size_mb

	column largest_table
		dataType: string
		sourceColumn: largest_table

	measure 'SQL Pool Count' = COUNTROWS('sql_pools')

	partition sql_pools = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataFolder & "sql_pools.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true])
			in
			    Headers
